# Generated by Django 5.0.6 on 2024-06-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('producto', models.CharField(choices=[('Jarras', 'Jarras'), ('Vasos', 'Vasos'), ('Platos', 'Platos'), ('Catrinas', 'Catrinas'), ('Bolsos', 'Bolsos'), ('Suter', 'Suter')], default='Artesania', max_length=20, verbose_name='Producto')),
                ('precio', models.PositiveIntegerField(default=0)),
                ('correo', models.EmailField(default='example@example.com', max_length=254)),
                ('descripcion', models.TextField(default='Descripcion')),
                ('numero', models.CharField(max_length=15)),
                ('facebook', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created'],
            },
        ),
    ]
