# Generated by Django 5.0.6 on 2024-07-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='numero',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='producto',
            field=models.TextField(default='producto'),
        ),
    ]
