# Generated by Django 5.0.6 on 2024-07-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_articulos_correo_remove_articulos_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='imagen',
        ),
    ]
