# Generated by Django 5.0.6 on 2024-07-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='producto',
            field=models.TextField(default='producto'),
        ),
    ]
